services:
  node-app :
    container_name: secondcontainer
    ports:
      - "4000:4000"
  nginx:
   image: nginx:stable-alpine
   ports:
    - "80:80"
   volumes:
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  #  environment:
  #  - NGINX_HOST=foobar.com
  #  - NGINX_PORT=80
